### PR TITLE
Add/docker

### PR DESCRIPTION
**Pull request by vsoch**
Hey @earcanal ! Okay here is our testing container! This should work with the breath-counting-task container, for example (and I have some changes for it that I'll address there later) to run the tests, you would cd into the base of the repo and map the directory with the package to `/data` in the container (see the updated README.md here for full description, and I put the container on docker hub so you can try it out:

```bash
docker run -v $PWD:/stroopr:/data vanessa/expfactory-r test:dev
```

Container is here --> https://hub.docker.com/r/vanessa/expfactory-r/ and the dev tag is what you can test. It just ran for me with the above and the breathing task, take a look and let me know if it is what you had in mind (and other entrypoints you might want to add other than "test")

### CODE REVIEW

**Comment by earcanal** [comment]
```
$ docker run -v $PWD:/expfactory-breathcounting:/data vanessa/expfactory-r test:dev
Unable to find image 'vanessa/expfactory-r:latest' locally
docker: Error response from daemon: manifest for vanessa/expfactory-r:latest not found.
```

**Comment by vsoch** [comment]
Just a stupid typo on my part!

```
docker run -v $PWD:/stroopr:/data vanessa/expfactory-r:dev test
```

**Comment by vsoch** [comment]
Also (not yet but with a subequent build) I'm going to switch the repo to --> https://hub.docker.com/r/expfactory/expfactoryr/

**Comment by vsoch** [comment]
hey @earcanal is this a good base container to build from? --> https://hub.docker.com/r/rocker/tidyverse/tags/

Also - how do we manage / maintain this package (via CRAN?) I've never done this before, but I bet we can do it on here :)

**Comment by vsoch** [comment]
wicked! Check this out! https://circleci.com/gh/expfactory/expfactoryr/3

**Comment by vsoch** [comment]
okay here are the issues I see

```
* checking DESCRIPTION meta-information ... WARNING
Non-standard license specification:
  BSD 3-Clause License
```
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'process_expfactory_survey'
  ‘flat’
Documented arguments not in \usage in documentation object 'process_expfactory_survey':
  ‘flat=FALSE’
```
and we likely need to ignore these guys

```
checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .circleci
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.

checking top-level files ... NOTE
Non-standard files/directories found at top level:
  ‘CHANGELOG.md’ ‘docker’ ‘Dockerfile’

checking R code for possible problems ... NOTE
process_expfactory_survey: no visible global function definition for
  ‘%>%’
process_expfactory_survey: no visible global function definition for
  ‘stack’
process_expfactory_survey: no visible global function definition for
  ‘rename’
process_expfactory_survey: no visible binding for global variable
  ‘values’
process_expfactory_survey: no visible global function definition for
... 17 lines ...
  ‘Token’
process_expfactory_survey: no visible binding for global variable
  ‘question’
Undefined global functions or variables:
  %>% filter ind key mutate name question rename select spread stack
  text Token value values
Consider adding
  importFrom("graphics", "text")
  importFrom("stats", "filter")
  importFrom("utils", "stack")
to your NAMESPACE file.
```
I think most of these are minor - I just fixed the LICENSE warning and you can take a look at the others later if you want to tweak things. I'm going to merge to test the deployment step, and then take a look at the next repo in the queue!

**Pull request merged**
